M48
; DRILL file {KiCad (6.0.4)} date Tue 12 Apr 2022 10:07:39 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-12T10:07:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.9016Y-1.9488
X4.9016Y-4.6457
X7.6378Y-1.9488
X7.6378Y-4.6457
T2
X6.4764Y-3.2508
X6.9291Y-3.2508
T0
M30
