M48
; DRILL file {KiCad 6.0.4} date Wed 27 Apr 2022 02:32:14 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-27T14:32:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.9016Y-1.9488
X4.9016Y-4.6457
X7.6378Y-1.9488
X7.6378Y-4.6457
T0
M30
